// Code generated by protoc-gen-go. DO NOT EDIT.
// source: net/redeemer.proto

package net

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MaxFloatReq struct {
	Sender               []byte   `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MaxFloatReq) Reset()         { *m = MaxFloatReq{} }
func (m *MaxFloatReq) String() string { return proto.CompactTextString(m) }
func (*MaxFloatReq) ProtoMessage()    {}
func (*MaxFloatReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_41a074e4ea0232f2, []int{0}
}

func (m *MaxFloatReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MaxFloatReq.Unmarshal(m, b)
}
func (m *MaxFloatReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MaxFloatReq.Marshal(b, m, deterministic)
}
func (m *MaxFloatReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MaxFloatReq.Merge(m, src)
}
func (m *MaxFloatReq) XXX_Size() int {
	return xxx_messageInfo_MaxFloatReq.Size(m)
}
func (m *MaxFloatReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MaxFloatReq.DiscardUnknown(m)
}

var xxx_messageInfo_MaxFloatReq proto.InternalMessageInfo

func (m *MaxFloatReq) GetSender() []byte {
	if m != nil {
		return m.Sender
	}
	return nil
}

type Ticket struct {
	TicketParams         *TicketParams           `protobuf:"bytes,1,opt,name=ticket_params,json=ticketParams,proto3" json:"ticket_params,omitempty"`
	Sender               []byte                  `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	ExpirationParams     *TicketExpirationParams `protobuf:"bytes,3,opt,name=expiration_params,json=expirationParams,proto3" json:"expiration_params,omitempty"`
	SenderParams         *TicketSenderParams     `protobuf:"bytes,4,opt,name=sender_params,json=senderParams,proto3" json:"sender_params,omitempty"`
	RecipientRand        []byte                  `protobuf:"bytes,5,opt,name=recipient_rand,json=recipientRand,proto3" json:"recipient_rand,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Ticket) Reset()         { *m = Ticket{} }
func (m *Ticket) String() string { return proto.CompactTextString(m) }
func (*Ticket) ProtoMessage()    {}
func (*Ticket) Descriptor() ([]byte, []int) {
	return fileDescriptor_41a074e4ea0232f2, []int{1}
}

func (m *Ticket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ticket.Unmarshal(m, b)
}
func (m *Ticket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ticket.Marshal(b, m, deterministic)
}
func (m *Ticket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ticket.Merge(m, src)
}
func (m *Ticket) XXX_Size() int {
	return xxx_messageInfo_Ticket.Size(m)
}
func (m *Ticket) XXX_DiscardUnknown() {
	xxx_messageInfo_Ticket.DiscardUnknown(m)
}

var xxx_messageInfo_Ticket proto.InternalMessageInfo

func (m *Ticket) GetTicketParams() *TicketParams {
	if m != nil {
		return m.TicketParams
	}
	return nil
}

func (m *Ticket) GetSender() []byte {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *Ticket) GetExpirationParams() *TicketExpirationParams {
	if m != nil {
		return m.ExpirationParams
	}
	return nil
}

func (m *Ticket) GetSenderParams() *TicketSenderParams {
	if m != nil {
		return m.SenderParams
	}
	return nil
}

func (m *Ticket) GetRecipientRand() []byte {
	if m != nil {
		return m.RecipientRand
	}
	return nil
}

type QueueTicketRes struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueueTicketRes) Reset()         { *m = QueueTicketRes{} }
func (m *QueueTicketRes) String() string { return proto.CompactTextString(m) }
func (*QueueTicketRes) ProtoMessage()    {}
func (*QueueTicketRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_41a074e4ea0232f2, []int{2}
}

func (m *QueueTicketRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueueTicketRes.Unmarshal(m, b)
}
func (m *QueueTicketRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueueTicketRes.Marshal(b, m, deterministic)
}
func (m *QueueTicketRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueueTicketRes.Merge(m, src)
}
func (m *QueueTicketRes) XXX_Size() int {
	return xxx_messageInfo_QueueTicketRes.Size(m)
}
func (m *QueueTicketRes) XXX_DiscardUnknown() {
	xxx_messageInfo_QueueTicketRes.DiscardUnknown(m)
}

var xxx_messageInfo_QueueTicketRes proto.InternalMessageInfo

type MonitorMaxFloatReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MonitorMaxFloatReq) Reset()         { *m = MonitorMaxFloatReq{} }
func (m *MonitorMaxFloatReq) String() string { return proto.CompactTextString(m) }
func (*MonitorMaxFloatReq) ProtoMessage()    {}
func (*MonitorMaxFloatReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_41a074e4ea0232f2, []int{3}
}

func (m *MonitorMaxFloatReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MonitorMaxFloatReq.Unmarshal(m, b)
}
func (m *MonitorMaxFloatReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MonitorMaxFloatReq.Marshal(b, m, deterministic)
}
func (m *MonitorMaxFloatReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MonitorMaxFloatReq.Merge(m, src)
}
func (m *MonitorMaxFloatReq) XXX_Size() int {
	return xxx_messageInfo_MonitorMaxFloatReq.Size(m)
}
func (m *MonitorMaxFloatReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MonitorMaxFloatReq.DiscardUnknown(m)
}

var xxx_messageInfo_MonitorMaxFloatReq proto.InternalMessageInfo

type MaxFloatUpdate struct {
	Sender               []byte   `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	MaxFloat             []byte   `protobuf:"bytes,2,opt,name=max_float,json=maxFloat,proto3" json:"max_float,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MaxFloatUpdate) Reset()         { *m = MaxFloatUpdate{} }
func (m *MaxFloatUpdate) String() string { return proto.CompactTextString(m) }
func (*MaxFloatUpdate) ProtoMessage()    {}
func (*MaxFloatUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_41a074e4ea0232f2, []int{4}
}

func (m *MaxFloatUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MaxFloatUpdate.Unmarshal(m, b)
}
func (m *MaxFloatUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MaxFloatUpdate.Marshal(b, m, deterministic)
}
func (m *MaxFloatUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MaxFloatUpdate.Merge(m, src)
}
func (m *MaxFloatUpdate) XXX_Size() int {
	return xxx_messageInfo_MaxFloatUpdate.Size(m)
}
func (m *MaxFloatUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_MaxFloatUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_MaxFloatUpdate proto.InternalMessageInfo

func (m *MaxFloatUpdate) GetSender() []byte {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *MaxFloatUpdate) GetMaxFloat() []byte {
	if m != nil {
		return m.MaxFloat
	}
	return nil
}

func init() {
	proto.RegisterType((*MaxFloatReq)(nil), "net.MaxFloatReq")
	proto.RegisterType((*Ticket)(nil), "net.Ticket")
	proto.RegisterType((*QueueTicketRes)(nil), "net.QueueTicketRes")
	proto.RegisterType((*MonitorMaxFloatReq)(nil), "net.MonitorMaxFloatReq")
	proto.RegisterType((*MaxFloatUpdate)(nil), "net.MaxFloatUpdate")
}

func init() { proto.RegisterFile("net/redeemer.proto", fileDescriptor_41a074e4ea0232f2) }

var fileDescriptor_41a074e4ea0232f2 = []byte{
	// 333 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xc1, 0x4e, 0xc2, 0x40,
	0x10, 0x86, 0x29, 0x28, 0xc1, 0x29, 0xd4, 0x32, 0x1a, 0x25, 0x70, 0x31, 0x4d, 0x48, 0x3c, 0xa1,
	0x42, 0xe2, 0xc9, 0x9b, 0xc1, 0x78, 0x21, 0xd1, 0xaa, 0xe7, 0x66, 0xa5, 0x63, 0xd2, 0x48, 0xb7,
	0xeb, 0x76, 0x48, 0x78, 0x03, 0x9f, 0xca, 0x77, 0x33, 0x6c, 0x5b, 0xb2, 0xd6, 0x70, 0xeb, 0x3f,
	0xf3, 0xcf, 0xd7, 0x7f, 0xa6, 0x05, 0x94, 0xc4, 0x57, 0x9a, 0x62, 0xa2, 0x94, 0xf4, 0x44, 0xe9,
	0x8c, 0x33, 0x6c, 0x49, 0xe2, 0xa1, 0xbf, 0x6d, 0xac, 0x54, 0xa4, 0xd5, 0xb2, 0x28, 0x07, 0x63,
	0x70, 0x17, 0x62, 0xf3, 0xb0, 0xca, 0x04, 0x87, 0xf4, 0x85, 0x67, 0xd0, 0xce, 0x49, 0xc6, 0xa4,
	0x07, 0xce, 0x85, 0x73, 0xd9, 0x0d, 0x4b, 0x15, 0x7c, 0x37, 0xa1, 0xfd, 0x9a, 0x2c, 0x3f, 0x89,
	0xf1, 0x16, 0x7a, 0x6c, 0x9e, 0x22, 0x25, 0xb4, 0x48, 0x73, 0xe3, 0x74, 0xa7, 0xfd, 0x89, 0x24,
	0x9e, 0x14, 0x9e, 0x27, 0xd3, 0x08, 0xbb, 0x6c, 0x29, 0x0b, 0xdd, 0xb4, 0xd1, 0xf8, 0x08, 0x7d,
	0xda, 0xa8, 0x44, 0x0b, 0x4e, 0x32, 0x59, 0x31, 0x5b, 0x86, 0x39, 0xb2, 0x98, 0xf3, 0x9d, 0xa7,
	0xa4, 0xfb, 0x54, 0xab, 0xe0, 0x1d, 0xf4, 0x0a, 0x66, 0x45, 0x39, 0x30, 0x94, 0x73, 0x8b, 0xf2,
	0x62, 0xfa, 0x55, 0xbe, 0xdc, 0x52, 0x38, 0x06, 0x4f, 0xd3, 0x32, 0x51, 0x09, 0x49, 0x8e, 0xb4,
	0x90, 0xf1, 0xe0, 0xd0, 0xe4, 0xec, 0xed, 0xaa, 0xa1, 0x90, 0x71, 0xe0, 0x83, 0xf7, 0xbc, 0xa6,
	0x35, 0x15, 0xbc, 0x90, 0xf2, 0xe0, 0x14, 0x70, 0x91, 0xc9, 0x84, 0x33, 0x6d, 0x5d, 0x32, 0x98,
	0x83, 0x57, 0xc9, 0x37, 0x15, 0x0b, 0xa6, 0x7d, 0xb7, 0xc5, 0x11, 0x1c, 0xa5, 0x62, 0x13, 0x7d,
	0x6c, 0xad, 0xe5, 0x6d, 0x3a, 0x69, 0x39, 0x3a, 0xfd, 0x71, 0xc0, 0xab, 0x5e, 0x55, 0x7c, 0x4f,
	0xbc, 0x01, 0xd7, 0x4a, 0x80, 0xae, 0xb5, 0xde, 0xf0, 0xc4, 0x88, 0x5a, 0xc0, 0x06, 0xce, 0xa0,
	0x53, 0x85, 0x41, 0xdf, 0x58, 0xac, 0xa8, 0xe5, 0xd0, 0xdf, 0xb4, 0x41, 0x03, 0xef, 0xe1, 0xb8,
	0xb6, 0x17, 0x16, 0xa7, 0xfc, 0xbf, 0xed, 0x1e, 0xc4, 0xb5, 0xf3, 0xde, 0x36, 0xbf, 0xd9, 0xec,
	0x37, 0x00, 0x00, 0xff, 0xff, 0x15, 0x09, 0xc1, 0x0c, 0x93, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TicketRedeemerClient is the client API for TicketRedeemer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TicketRedeemerClient interface {
	QueueTicket(ctx context.Context, in *Ticket, opts ...grpc.CallOption) (*QueueTicketRes, error)
	MaxFloat(ctx context.Context, in *MaxFloatReq, opts ...grpc.CallOption) (*MaxFloatUpdate, error)
	MonitorMaxFloat(ctx context.Context, in *MonitorMaxFloatReq, opts ...grpc.CallOption) (TicketRedeemer_MonitorMaxFloatClient, error)
}

type ticketRedeemerClient struct {
	cc *grpc.ClientConn
}

func NewTicketRedeemerClient(cc *grpc.ClientConn) TicketRedeemerClient {
	return &ticketRedeemerClient{cc}
}

func (c *ticketRedeemerClient) QueueTicket(ctx context.Context, in *Ticket, opts ...grpc.CallOption) (*QueueTicketRes, error) {
	out := new(QueueTicketRes)
	err := c.cc.Invoke(ctx, "/net.TicketRedeemer/QueueTicket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketRedeemerClient) MaxFloat(ctx context.Context, in *MaxFloatReq, opts ...grpc.CallOption) (*MaxFloatUpdate, error) {
	out := new(MaxFloatUpdate)
	err := c.cc.Invoke(ctx, "/net.TicketRedeemer/MaxFloat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketRedeemerClient) MonitorMaxFloat(ctx context.Context, in *MonitorMaxFloatReq, opts ...grpc.CallOption) (TicketRedeemer_MonitorMaxFloatClient, error) {
	stream, err := c.cc.NewStream(ctx, &_TicketRedeemer_serviceDesc.Streams[0], "/net.TicketRedeemer/MonitorMaxFloat", opts...)
	if err != nil {
		return nil, err
	}
	x := &ticketRedeemerMonitorMaxFloatClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TicketRedeemer_MonitorMaxFloatClient interface {
	Recv() (*MaxFloatUpdate, error)
	grpc.ClientStream
}

type ticketRedeemerMonitorMaxFloatClient struct {
	grpc.ClientStream
}

func (x *ticketRedeemerMonitorMaxFloatClient) Recv() (*MaxFloatUpdate, error) {
	m := new(MaxFloatUpdate)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TicketRedeemerServer is the server API for TicketRedeemer service.
type TicketRedeemerServer interface {
	QueueTicket(context.Context, *Ticket) (*QueueTicketRes, error)
	MaxFloat(context.Context, *MaxFloatReq) (*MaxFloatUpdate, error)
	MonitorMaxFloat(*MonitorMaxFloatReq, TicketRedeemer_MonitorMaxFloatServer) error
}

// UnimplementedTicketRedeemerServer can be embedded to have forward compatible implementations.
type UnimplementedTicketRedeemerServer struct {
}

func (*UnimplementedTicketRedeemerServer) QueueTicket(ctx context.Context, req *Ticket) (*QueueTicketRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueueTicket not implemented")
}
func (*UnimplementedTicketRedeemerServer) MaxFloat(ctx context.Context, req *MaxFloatReq) (*MaxFloatUpdate, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MaxFloat not implemented")
}
func (*UnimplementedTicketRedeemerServer) MonitorMaxFloat(req *MonitorMaxFloatReq, srv TicketRedeemer_MonitorMaxFloatServer) error {
	return status.Errorf(codes.Unimplemented, "method MonitorMaxFloat not implemented")
}

func RegisterTicketRedeemerServer(s *grpc.Server, srv TicketRedeemerServer) {
	s.RegisterService(&_TicketRedeemer_serviceDesc, srv)
}

func _TicketRedeemer_QueueTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Ticket)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketRedeemerServer).QueueTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/net.TicketRedeemer/QueueTicket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketRedeemerServer).QueueTicket(ctx, req.(*Ticket))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketRedeemer_MaxFloat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MaxFloatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketRedeemerServer).MaxFloat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/net.TicketRedeemer/MaxFloat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketRedeemerServer).MaxFloat(ctx, req.(*MaxFloatReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketRedeemer_MonitorMaxFloat_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MonitorMaxFloatReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TicketRedeemerServer).MonitorMaxFloat(m, &ticketRedeemerMonitorMaxFloatServer{stream})
}

type TicketRedeemer_MonitorMaxFloatServer interface {
	Send(*MaxFloatUpdate) error
	grpc.ServerStream
}

type ticketRedeemerMonitorMaxFloatServer struct {
	grpc.ServerStream
}

func (x *ticketRedeemerMonitorMaxFloatServer) Send(m *MaxFloatUpdate) error {
	return x.ServerStream.SendMsg(m)
}

var _TicketRedeemer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "net.TicketRedeemer",
	HandlerType: (*TicketRedeemerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueueTicket",
			Handler:    _TicketRedeemer_QueueTicket_Handler,
		},
		{
			MethodName: "MaxFloat",
			Handler:    _TicketRedeemer_MaxFloat_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "MonitorMaxFloat",
			Handler:       _TicketRedeemer_MonitorMaxFloat_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "net/redeemer.proto",
}
